version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: "disabled"
  ignore:
  # These update basically every day, and 99.9% of the time we don't care
  - dependency-name: "boto3"
  - dependency-name: "boto3-stubs"
  - dependency-name: "botocore"
  - dependency-name: "botocore-stubs"
